name: vacuum_persistent
version: 2.0.0
author: see AUTHORS
description: Efficient persistent data structures for Dart
homepage: https://github.com/vacuumlabs/persistent

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  quiver: ">=0.18.0 <1.0.0"

dev_dependencies:
  benchmark_harness: ^1.0.5
  test: ^1.15.4
